export const ASYNC_START = 'ASYNC_START';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const REGISTER_NEW_USER = 'REGITER_NEW_USER';
export const SET_REGISTER_ERROR_TRUE = 'SET_REGISTER_ERROR_TRUE';
export const SET_REGISTER_ERROR_FALSE = 'SET_REGISTER_ERROR_FALSE';
export const DELETE_LISTING = 'DELETE_LISTING';

export const SET_CREATE_LISTING_ERROR_TRUE = 'SET_CREATE_LISTING_ERROR_TRUE'
export const ADD_LISTING_TO_USER = 'ADD_LISTING_TO_USER'
